# This file configures the Gitpod workspace.
# For more details, see https://www.gitpod.io/docs/configure/workspaces/gitpod-yml

tasks:
  - name: Dependencies and Database Setup
    before: |
      echo "--- Step 1: Updating npm ---"
      npm install -g npm@latest
      echo "--- Step 2: Installing project dependencies ---"
      npm install
      echo "--- Step 3: Starting PostgreSQL ---"
      pg_ctl -D $PGDATA -l postgres.log start
      echo "--- Step 4: Creating database 'automatic' ---"
      createdb -U gitpod automatic || echo "Database 'automatic' already exists. Skipping."
    init: |
      echo "--- Step 5: Running Prisma migrations ---"
      npx prisma migrate dev --name init
    command: |
      echo "--- Step 6: Starting Next.js development server ---"
      npm run dev

ports:
  - port: 5432
    onOpen: ignore
    visibility: private
  - port: 3000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - prisma.prisma
    - esbenp.prettier-vscode
